//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.Transactions = new HashSet<Transactions>();
        }
        
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        [Required]
        public int Typ_Id { get; set; }
        [Required]
        public int Typ_Id2 { get; set; }
        [Required]
        public int AccNum { get; set; }
        [Required]
        public int C_Id { get; set; }
        [Required]
        public decimal Balance { get; set; }
        [Required]
        public int AccNum2 { get; set; }
      
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
