//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Branch { get; set; }
        public string Phone { get; set; }
        public decimal Salary { get; set; }
    }
}
